---
- name: Update proxy in /etc/yum.conf
  lineinfile:
    path: /etc/yum.conf
    line: proxy={{ http_proxy }}
    create: true

- name: Update proxy in /etc/dnf/dnf.conf
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: proxy={{ http_proxy }}
    create: true