---
- name: Update proxy in /etc/apt/apt.conf.d/proxy.conf
  blockinfile:
    path: /etc/apt/apt.conf.d/proxy.conf
    create: true
    block: |
      Acquire::http::Proxy "{{ http_proxy }}";
      Acquire::https::Proxy "{{ https_proxy }}";
      Acquire::ftp::Proxy "{{ ftp_proxy }}";