---
- name: Converge
  hosts: all
  vars:
    users:
      - root
      - tomereli

  pre_tasks:
    - name: Ensure {{ username }} user exists
      user:
        name: "{{ username }}"
        state: present
      loop: '{{ users }}'
      loop_control:
        loop_var: 'username'
      when: users is defined
    
  roles:
    - role: tomereli.proxy
      vars:
        http_proxy: 'http://example-proxy-server.com:911/'
        https_proxy: 'http://example-proxy-server.com:911/'
        ftp_proxy: 'http://example-proxy-server.com:911/'
        no_proxy: 'localhost'
