---
- name: Converge
  hosts: all
  
  pre_tasks:
    - name: Ensure {{ username }} user exists
      user:
        name: "{{ username }}"
        state: present
    
  roles:
    - role: tomereli.proxy
      vars:
        username: tbeliyah
        http_proxy: "{{ ansible_env.http_proxy | default('http://example-proxy-server.com:911/') }}"
        https_proxy: "{{ ansible_env.https_proxy | default('http://example-proxy-server.com:911/') }}"
        ftp_proxy: "{{ ansible_env.ftp_proxy | default('http://example-proxy-server.com:911/') }}"
        no_proxy: "{{ ansible_env.no_proxy | default('localhost') }}"