---
- name: Converge
  hosts: all
  vars:
    users:
      - username: root
      - username: tomereli
      - username: romi

  pre_tasks:
    - name: Ensure user exists
      user:
        name: "{{item.username}}"
        state: present
      with_items: "{{users}}"
      when: users is defined
    
  roles:
    - role: tomereli.proxy
      vars:
        http_proxy: 'http://example-proxy-server.com:911/'
        https_proxy: 'http://example-proxy-server.com:911/'
        ftp_proxy: 'http://example-proxy-server.com:911/'
        no_proxy: 'localhost'
